//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backendkyrios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class membros
    {
        public int idMembro { get; set; }
        public string nomeMembro { get; set; }
        public string enderMembro { get; set; }
        public Nullable<System.DateTime> dataNascMembro { get; set; }
        public string telResMembro { get; set; }
        public string emailMembro { get; set; }
        public Nullable<bool> batizadoMembro { get; set; }
        public string telCelMembro { get; set; }
        public string bairroMembro { get; set; }
        public string cepMembro { get; set; }
        public string ufMembro { get; set; }
        public string sexoMembro { get; set; }
        public string cidadeMembro { get; set; }
    }
}
